 - name: Create server in AWS 
   tags: ec2
   local_action:
     module: ec2
     region: us-west-2
     image: ami-d732f0b7
     key_name: compucorp
     vpc_subnet_id: subnet-4d735429
     group: compucorp-sg
     instance_type: t2.micro
     wait: yes
     assign_public_ip: yes
     count: 1
